version: '3.9'

services:
  server:
    container_name: cassiofernando
    image: alpine:latest
    working_dir: /cassiofernando
    command: sh ./docker-start.sh
    volumes:
      - './:/cassiofernando'
    ports:
      - '1313:1313'
